language: go
go:
- 1.12.x
script:
- go build -o approle-login-$(go env GOOS)-$(go env GOARCH)
arch:
- amd64
- arm64
os: linux
deploy:
  provider: releases
  file: approle-login-*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: XD3ekWGj8T7mdDVfjfuFmBJIiwvwSUiQr94B2d6zsd+i/ZjzUbhaWP5+Jeutl9xPI+0uqXCE8fOVwZmj7iJsl4mXWV+eiAPJRBxLImGWUBePIdPF0/y30vxFz25HXUGpY2w5auviRUs1nP9WUuINKtQ6YF9BFZJ6m4RSNAuHr0WDxEvRrlWFfygsvFRIosyjjli7IcTr54l3B5SYVKQiJaZEYCkwQATO7bYgfzAjFUp+TlXLRJ6hYQEBQdnpI7TwYpEPgYncH5GPTJySLaZy1x7Rw8csm4oQ6OgT+QXUGVJ6UI62CMx0SELqzWXNjo07Xfi4QiyRSzaHrOk3zRSXuo+0IMbJfEaAM5C3yhT4WMr2Vv6F7HgT+2ofe4hdZ8qadvuFJeG0PTd07pmFzolxqkxhumA6PTNydJzLmL/4YGwzcrp1go91oNbrDBquJDmPb7HLhoS287sJhF5YaeL+F0+5FTxLqqrQyj0HZ81k4efTRXCsk14RMjwJ+N8xLHHeW2BWav79vF03evoORuVBxCvExfmw1EliSRjNEm7yRunBbOUaYMHYrKgIdl7i8kySR0hETlbsjEr4Lx0nuhFFvtUKPkkljHlIZJsw4G9RYJk7q7uiloLW+VeRpXFUPqsFf7BH4OmWYgFg+icVQZnaU1KsWQxvaGNBqaOXnqoeJ3Y=
